### PR TITLE
Restyling onetime-payment.html

### PR DESCRIPTION
**Pull request by maahir22**
Added CSS fonts to maintain similarity in outlook( With fallback fonts ).
Alignment at the centre of the page.
Minor change of button display design.

### CODE REVIEW

**Comment by maahir22** [comment]
Updated view : 
Screen Shot 2020-10-05 at 2 50 06 AM

Old View -
Screen Shot 2020-10-05 at 2 53 52 AM

**Comment by maahir22** [comment]
@mikemccamon Please have a look.

**Comment by bkimminich** [comment]
This change makes it look nicer, but isn't it also breaking consistency across other pages? I don't really see the point to make this singular change. Improving the global CSS for the entire website would be preferable and more consistent. Correct me if I'm not seeing a bigger picture here.

**Comment by hblankenship** [comment]
I am in agreement with Bjoern.  This breaks consistency, even if it is 'nicer'.

**Comment by maahir22** [comment]
Thank you for your swift feedback. I'll be making a new PR once I've styled the Global CSS across all the pages, so that the styles are consistent.

**Pull request closed without merging**
