### PR TITLE
Update securetea to level 3 (projects.json)

### PR DESCRIPTION
**Pull request by adeyosemanputra**

### CODE REVIEW

**Comment by hblankenship** [comment]
You should not have to do this; the nightly builds should have updated the data but did not due to updating not working as expected. This should resolve tonight. If that isn't soon enough, I will merge this PR; just let me know.

**Comment by adeyosemanputra** [comment]
Hi Harold

it's still nor working, please help to review and merge

best,
ade yoseman

**Comment by hblankenship** [comment]
It worked over night, as expected.  Cheers.

**Comment by adeyosemanputra** [comment]
Cool, thank you Harold

**Pull request closed without merging**
