### PR TITLE
Removing inaccurate details from the website

### PR DESCRIPTION
**Pull request by anantshri**
The manage membership form is actually just view your membership. If we dont support a feature we should be clear about it and state it correctly. 

This is requested from staff since January 2020.  refer https://github.com/OWASP/owasp.github.io/issues/56 since staff is unwilling to accurately post information online. I am doing the edit and submitting the request for everyone's sake.

### CODE REVIEW

**Comment by kingthorin** [comment]
ping @hblankenship

**Comment by hblankenship** [comment]
No intent to alter language at this time and renewal is through the form as stated.  Can revisit if this becomes a major concern for more people.

**Comment by ThunderSon** [comment]
The proposed text is much more readable. I was extremely confused when I getting a membership, as the page was in no way actionable nor provided the things the text said it does.
It's really a simple readability update that helps the website. Why was it rejected? What's the basis for that?
Till there is actual **management** of the renewal and membership status, I believe this PR needs to be re-opened and properly discussed.

_Note:_ This is an issue that keeps coming up. The community needs a clean slate. Communication needs to be crystal clear. :smile:

**Comment by hblankenship** [comment]
There is management of the billing details and recurring portion of any recurring donation or membership.  I have updated the language slightly to reflect this.

**Pull request closed without merging**
