### PR TITLE
Update projects.md Add CycloneDX

### PR DESCRIPTION
**Pull request by northdpole**
this pr adds a CycloneDX link to the wayfinder
image

### CODE REVIEW

**Comment by northdpole** [comment]
image
closes https://github.com/OWASP/www-project-integration-standards/issues/49

**Comment by jgadsden** [comment]
Thanks also for adding Wrong Secrets, Coraza and Secure Headers 👍🏾

**Comment by righettod** [comment]
Thanks a lots 👍

**Comment by jgadsden** [comment]
@vanderaj or @hblankenship could you review this and merge please?
It adds the projects to the Wayfinder diagram, and this will then match up with the OWASP Developer Guide:

- CycloneDX
- Wrong Secrets
- Coraza
- Secure Headers

**Comment by righettod** [comment]
Thank you 👍

**Pull request merged**
