### PR TITLE
Added corresponding types so all Flagship projects get listed on Flagship tab.

### PR DESCRIPTION
**Pull request by martinmarsicano**
Add corresponding types in projects.json, so Mobile Top 10 and Security Knowledge Framework get listed on Flagship projects tab.

### CODE REVIEW

**Comment by martinmarsicano** [comment]
@hblankenship can you check this PR?
I also open a PR on SKF to correspond with this:
https://github.com/OWASP/www-project-security-knowledge-framework/pull/9

**Comment by martinmarsicano** [comment]
> @hblankenship can you check this PR?
> I also open a PR on SKF that is related to this:
> [OWASP/www-project-security-knowledge-framework#9](https://github.com/OWASP/www-project-security-knowledge-framework/pull/9)

This PR is already merged. So, this is good to go!

**Comment by martinmarsicano** [comment]
Or maybe @kingthorin is also able to do it?

**Comment by kingthorin** [comment]
The file has conflicts, likely due to the source fork being out of date (master vs main). [Plus people should really use feature branches for PRs.]

This file is generated, changing it manually will just get smashed at the next job run (midnight?)

The generation would need to be tweaked and I don't know where that is.

Lastly, no sorry I can't merge in this repo.

**Comment by martinmarsicano** [comment]
My bad missing the out of date fork. The only conflict Github show me was the json file itself. Will fix that.

So now the real question is, if this file is generated from an external system or if it could be changed manually. @hblankenship ?

If this could be changed manually, I will close this PR and generate the proper one.

**Comment by kingthorin** [comment]
I believe this job simply crawls all the www-project-* repos and looks at the level in the front matter of index.md. If there are flagships that aren’t included then they just need to properly list themselves based on the info from the migration page.
https://owasp.org/migration

**Comment by martinmarsicano** [comment]
Yes 😅, ZAP was one of the ones I check out.

**Comment by kingthorin** [comment]
Ya I just rechecked a few when u mentioned it 😀

**Comment by martinmarsicano** [comment]
Just finish doing the PR to each project, so now I just must wait for Harold or leaders to merge it and for the automated process to run. As always thank you @kingthorin for the help.

**Comment by martinmarsicano** [comment]
Confirmed! Level, type and pitch are gathered by the daemon from the meta tags of the index.md file

image

Will try to add the pitch for the one that hasn't one.

**Pull request closed without merging**
