### PR TITLE
Fix WSTG blog date

### PR DESCRIPTION
**Pull request by kingthorin**
In follow-up to https://github.com/OWASP/owasp.github.io/pull/126

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Review by ThunderSon — APPROVED** [review]
@hblankenship Please, when possible merge this to fix the blog release date.

**Review by ThunderSon — CHANGES_REQUESTED** [review]
Rename the file, that will change the link

**Review by ThunderSon — APPROVED** [review]

**Comment by kingthorin** [comment]
@hblankenship we had hoped to avoid doing this in two steps by asking questions on the first PR but then it was merged anyway. Please merge this to fix things up.

**Comment by kingthorin** [comment]
Thanks!

**Pull request merged**
