### PR TITLE
Update the data for secureCodeBox after site migration

### PR DESCRIPTION
**Pull request by Weltraumschaf**
- the name is strictly camel case: secureCodeBox
- add a pitch
- use region unknown as the most tools does (looks like region is for chapters)
- use level incubator

Signed-off-by: Sven Strittmatter <sven.strittmatter@iteratec.com>

### CODE REVIEW

**Comment by hblankenship** [comment]
This file is Auto generated nightly and does not require updates.  It will use the Title: of your project page when it updates.

**Comment by Weltraumschaf** [comment]
Ah, ok. And how do I set "region" and "level"? I poked around in the repo for documentaton, but didn't found.

**Comment by hblankenship** [comment]
It should have been in the default text in the info.md file:

level: For projects, this is your project level (2 - Incubator, 3 - Lab, 4
- Flagship)

type: For projects, one of documentation, code, or tool


You can ignore the region as it really only pertains to chapters but they
are: Africa, Asia, Oceania, Europe, North America, and South America


Cheers,

Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects

**Comment by Weltraumschaf** [comment]
Thanx, fixed it :-)

**Pull request closed without merging**
