### PR TITLE
Corrected Zap capitalization

### PR DESCRIPTION
**Pull request by psiinon**
Its always ZAP, never Zap ;)

### CODE REVIEW

**Comment by hblankenship** [comment]
Resolved via automation

**Comment by psiinon** [comment]
Except that it hasnt been resolved, at least not yet.
https://owasp.org/projects/#div-flagships still says "OWASP Zap"

**Comment by hblankenship** [comment]
Thanks.  Should be corrected with the next build.

**Comment by psiinon** [comment]
Fingers crossed then :)

**Comment by psiinon** [comment]
Its good now! Many thanks :)

**Pull request closed without merging**
