### PR TITLE
Add a description for the OWASP cheat sheet series project

### PR DESCRIPTION
**Pull request by rbsec**
Adds the following description for the cheat sheet project:

> The OWASP Cheat Sheet Series was created to provide a set of simple good practice guides for application developers and defenders to follow.

Including @ThunderSon for visibility.

### CODE REVIEW

**Comment by ThunderSon** [comment]
Oh wow, that file is a living sin.
@rbsec how about this:
> The OWASP Cheat Sheet Series project provides a set of concise best practice guides for application developers and defenders to follow.
Removes the `was created` and the sheets are somewhat `concise best practices` in security terms.

**Comment by rbsec** [comment]
@ThunderSon updated.

**Comment by hblankenship** [comment]
This file is auto-generated nightly.  The information should go in the front matter of the project index.md file labelled pitch:  (See OWASP Juice Shop, index.md, for example).

**Comment by rbsec** [comment]
@hblankenship thanks - I'll update it there instead.

**Pull request closed without merging**
